services:
  - type: web
    name: astralean-homes
    env: node
    region: oregon
    plan: free
    installCommand: npm install --production=false
    buildCommand: npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production

