services:
  - type: web
    name: astraleanhomes
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: ALLOWED_ORIGIN
        value: "*"
      - key: NODE_ENV
        value: "production"

